Update Tips.md
dappforce/subsocial-docs pull request #26
Opened 2021-11-22 21:33 UTC by Yung-Beef

2021-11-22 21:38 UTC, Yung-Beef commented
Monetization sub-section of Architecture

2022-01-21 12:51 UTC, F3Joule approved these changes

2022-01-21 12:51 UTC, F3Joule commented on docs/lightpaper/architecture/monetization/Tips.md
> +Tips will go straight to the account that you are tipping, and the tippee will receive the full value of the tip, as there are no middlemen to take a cut.
As stated, there will be no cut from the tip directly, but the sender will pay a fee for the blockchain operation, so in a result it sounds not fully clear.

2022-01-21 16:43 UTC, Yung-Beef commented on docs/lightpaper/architecture/monetization/Tips.md
> +Tips will go straight to the account that you are tipping, and the tippee will receive the full value of the tip, as there are no middlemen to take a cut.
Yeah but if I tip 1 KSM they get 1 KSM, I just pay 1.0001 KSM, so they still get the full value.

2022-01-21 17:34 UTC, Yung-Beef commented on docs/lightpaper/architecture/monetization/SocialTokens.md
> +or utilize Kusama's cross-chain messaging protocol to move those tokens to another chain that has a DEX.
Updated: https://github.com/dappforce/subsocial-docs/pull/26/commits/a70769ee68fa5da5116ca62720973850b9de3cc2

I think it committed to this PR right, please double check, Github still confuses me...

2022-04-12 21:17 UTC, siman approved these changes

2022-04-12 21:17 UTC, siman commented on docs/lightpaper/architecture/monetization/SmartContracts.md
> +or integrate with other parachains that support smart contracts, like Moonriver.
We are currently looking into ways to potentially integrate smart contract functionality into Subsocial.

2022-04-12 21:18 UTC, siman requested changes

2022-04-12 21:18 UTC, siman commented on docs/lightpaper/architecture/monetization/SmartContracts.md
> +or integrate with other parachains that support smart contracts, like Moonriver.
```suggestion
We are currently looking into ways to potentially integrate smart contract functionality into Subsocial.
```

2022-04-12 21:19 UTC, merged