Update AdvancedModeration.md
dappforce/subsocial-docs pull request #28
Opened 2021-11-22 21:42 UTC by Yung-Beef

2021-11-22 21:44 UTC, Yung-Beef commented
Beyond v1.0 section

2022-01-21 12:56 UTC, F3Joule requested changes

2022-01-21 12:56 UTC, F3Joule commented on docs/lightpaper/beyond-v1.0/Marketplace.md
> +The content that makes up our feeds on social networking websites is controlled by unseen
```suggestion
The content that makes up our feeds on centralized social networking platforms is controlled by unseen
```

2022-01-24 09:58 UTC, F3Joule approved these changes

2022-06-13 14:42 UTC, olehmell approved these changes

2022-06-13 14:42 UTC, merged