add TestNet details (SoonSocial)
dappforce/subsocial-docs pull request #46
Opened 2022-04-28 08:15 UTC by tusharojha

## Description

Added details about testnet and information about it's usage with SDK.

2022-04-28 14:13 UTC, Yung-Beef commented on docs/sdk/quick-start/AboutSoonsocialTestnet.md
> +Subsocial provides developer with a new and fast testnet for building and testing your social Dapps. It enables you to start building and deploy your dapp on our testnet and invite your early communi
```suggestion
Subsocial provides developers with a new and fast testnet (named Soonsocial, because testnet features will be on the mainnet soon) for building and testing your social Dapps. It enables you to start building and deploy your dapps on our testnet, and invite your early community to start using it without need to buy real SUB tokens on the mainnet.
```

2022-04-28 14:13 UTC, Yung-Beef commented on docs/sdk/quick-start/AboutSoonsocialTestnet.md
> +Tokens on testnet can be recieved by writing the following command in our discord server.
```suggestion
Tokens on the testnet can be received by writing the following command in our Discord server.
```

2022-04-29 10:41 UTC, tusharojha commented on docs/sdk/quick-start/AboutSoonsocialTestnet.md
> +The discord bot will grant you **10 SUB** tokens to test on the Soonsocial solochain.
Yes, if you go to polkadotjs apps you will see Soonsocial under testnets.

2022-04-29 12:27 UTC, olehmell requested changes

2022-06-13 14:42 UTC, olehmell approved these changes

2022-06-13 14:43 UTC, merged