Docs text improvements
dappforce/subsocial-docs pull request #56
Opened 2022-07-15 18:33 UTC by Yung-Beef

Updated and created new text to reflect the current status of the project and provide more detail, such as explaining how NRG will work and how content storage works.

Fixed some internal links.

2022-07-15 19:52 UTC, tusharojha requested changes
I have added a few comments. 

Additionally, it's good if we prefer adding the sidebar property in headers. There are these 4 types of sidebars:

- homeSidebar
- tutorialsSidebar
- developSidebar
- announcementSidebar

and at the top of any markdown file you can add it as follows:

`displayed_sidebar: developSidebar`

2022-07-15 19:52 UTC, tusharojha commented on docs/basics/faq/Overview.md
> +[Subsocial Lightpaper](/docs/basics/lightpaper/introduction)
Please reverse this change, the /docs/basics page takes user to introduction page only.

2022-07-15 19:52 UTC, tusharojha commented on sidebars.js
> +              "lightpaper/architecture/energy",
this should be `basics/lightpaper/architecture/energy`.

2022-07-15 19:52 UTC, tusharojha commented on docs/basics/tokenomics/Token-economics.md
> +See the [Lightpaper](/docs/basics/lightpaper/introduction) for greater details.
Reverse this change too.

2022-07-15 19:52 UTC, tusharojha commented on docs/basics/tokenomics/Resources.md
> +- ([Subsocial Lightpaper](/docs/basics/lightpaper/introduction))
Reverse it.

2022-07-18 10:54 UTC, tusharojha requested changes
Added a few more comments that are causing the build to fail.

2022-07-18 10:54 UTC, tusharojha commented on docs/basics/faq/Overview.md
> +A tutorial on how to install and use Polkadot.js is available [here](/docs/tutorials/getting-started/account-setup/polkadot-js).
Just use `docs/tutorials/`. Please copy the paths from docs.subsocial.network and remove base URL.

2022-07-18 10:54 UTC, tusharojha commented on docs/tutorials/TokenClaim.md
> +Yes, please see the tutorial [here](docs/tutorials/mobile-claim).
This page does not exist.

2022-07-18 14:58 UTC, Yung-Beef commented on docs/tutorials/TokenClaim.md
> +Yes, please see the tutorial [here](docs/tutorials/mobile-claim).
![image](https://user-images.githubusercontent.com/89395745/179540334-bede0188-74e2-4665-9014-5ce015f34f4a.png)
It does though, I've quadruple checked it

2022-07-18 16:06 UTC, olehmell approved these changes

2022-07-18 16:06 UTC, merged