added playground rules
dappforce/subsocial-docs pull request #61
Opened 2022-09-30 12:15 UTC by tusharojha

## Description

Added a doc about playground info, working, code behind inbuilt APIs, etc.

2022-10-09 17:25 UTC, tusharojha commented
@Yung-Beef please review.

2022-10-11 08:56 UTC, olehmell requested changes

2022-10-11 08:56 UTC, olehmell commented on docusaurus.config.js
> +        'We just launched the Subsocial Playground for developers, Try now <a target="_blank" rel="noopener noreferrer" href="https://docs.subsocial.network/playground">here</a>.',
```suggestion
        'We just launched the Subsocial Playground for developers, Try now <a target="_blank" rel="noopener noreferrer" href="https://play.subsocial.network">here</a>.',
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +Subsocial Playground is an easy tool that allows you to run code snippets from our SDK without downloading anything.
```suggestion
Subsocial's Playground is an easy tool that allows you to run code snippets from our SDK without downloading anything.
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +It's running on our Testnet called Soonsocial. You can get some test tokens from our [discord bot](https://discord.gg/JRTMTtPK).
```suggestion
The Playground is running on our Testnet called Soonsocial. You can get some test tokens from our [Discord bot](https://discord.gg/JRTMTtPK).
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +The Playground provides a perfect environment to play, test and debug some of your code snippets before building a real project.
```suggestion
This provides a perfect environment to play, test and debug some of your code snippets before building a real project. 
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +### Tryout the playground: [Subsocial Playground](https://docs.subsocial.network/playground).
```suggestion
### Try out the [Subsocial Playground](https://docs.subsocial.network/playground).
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +## In-built APIs
```suggestion
## Built-in APIs
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +The Subsocial Playground comes with Subsocial SDK's `api` instance. This is use to interact with most of the SDK methods, here's how it's being created underhood:
```suggestion
The Subsocial Playground comes with the Subsocial SDK's `api` instance. This is used to interact with most of the SDK methods. Here is how it's being created under the hood:
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +Make sure to run local Subsocial & IPFS node before using these configs in your project.
```suggestion
Make sure to run local Subsocial & IPFS nodes before using these configs in your project.
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +The Subsocial Playground comes with CRUST IPFS API used as `ipfs` instance. This is use to store data related spaces, posts and comments on the network. Let's see how the configuration is set:
```suggestion
The Subsocial Playground comes with the CRUST IPFS API's `ipfs` instance. This is use to store data related spaces, posts and comments on the network. Let's see how the configuration is set:
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +The Subsocial Playground comes with a basic `keyring` instance to help you sign and send transactions. By default, we use the Alice (Test) account for our Testnet transactions but you can change it i
```suggestion
The Subsocial Playground comes with a basic `keyring` instance to help you sign and send transactions. By default, we use the Alice (Test) account for our Testnet transactions, but you can change it if you want. 
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +The Subsocial Playground allows you to sign and send the transaction through Mnemonic using Keyring and Polkadot.js extension both.
```suggestion
The Subsocial Playground allows you to sign and send transactions with Mnemonic phrases using both Keyring and the Polkadot.js extension. 
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +To sign and send transactions using Keyring through Mnemonic, use:
```suggestion
To sign and send transactions with Mnemonic phrases through Keyring, use:
```

2022-10-11 19:16 UTC, Yung-Beef commented on docs/develop/Playground.md
> +Signing using the polkadot.js extension:
```suggestion
Signing using the Polkadot.js extension: 
```

2022-10-12 11:38 UTC, merged