Updated docs with new SDK version details
dappforce/subsocial-docs pull request #62
Opened 2022-10-10 13:38 UTC by tusharojha

Updates include:
- Quick Reference guide, checked and updated.
- Intro & Getting started related docs

Working on how to guide, will create separate PR for it.

2022-10-10 13:41 UTC, tusharojha commented
@olehmell @Yung-Beef please review.

2022-10-11 09:06 UTC, olehmell requested changes

2022-10-11 09:06 UTC, olehmell commented on docs/develop/how-to-guides/ConnectToSubsocial.md
> +  const substrateApi = await api.blockchain.api
```suggestion
  const substrateApi = await api.substrateApi
```

2022-10-11 19:04 UTC, Yung-Beef commented on docs/develop/getting-started/APITypes.md
> +Subsocial API creates a new connection to the blcokchain and provides a list of methods that help in fetching and writing data on substrate pallets. It uses proper types for javascript and are easy f
```suggestion
Subsocial API creates a new connection to the blockchain and provides a list of methods that help in fetching and writing data on substrate pallets. It uses proper types for javascript and is easy for developing most social Dapps.
```

2022-10-11 19:05 UTC, Yung-Beef commented on docs/develop/getting-started/APITypes.md
> +Core SubsocialApi provides you with detailed methods for interacting with Subsocial blockchain.
```suggestion
The core SubsocialApi provides you with detailed methods for interacting with the Subsocial blockchain. 
```

2022-10-11 19:07 UTC, Yung-Beef commented on docs/develop/how-to-guides/ConnectToSubsocial.md
> +needs the Substrate node URL, offchain URL, and IPFS node URL. After initialization, api can be
```suggestion
needs the Substrate node URL, offchain URL, and IPFS node URL. After initialization, the API can be
```

2022-10-12 07:16 UTC, tusharojha commented on docs/develop/getting-started/APITypes.md
> +You can access it from the SubsocialApi object like this: `api.subsocial`.
base subsocial API.

2022-10-12 11:38 UTC, merged