Update Docs Develop Section for SDK inconsistency
dappforce/subsocial-docs pull request #65
Opened 2022-11-14 21:39 UTC by 0xMenna01

2022-11-14 22:55 UTC, olehmell requested changes

2022-11-14 22:55 UTC, olehmell commented on docs/develop/QuickReference.md
> +  const substrateApi = await api.blockchain.api
```suggestion
  const substrateApi = await api.substrateApi
```

2022-11-14 22:55 UTC, olehmell commented on docs/develop/how-to-guides/ConnectToSubsocial.md
> +/* import newSubsocialApi and util functions */
```suggestion
/* import SubsocialApi and util functions */
```

2022-11-14 22:55 UTC, olehmell commented on docs/develop/how-to-guides/profiles/CreateProfiles.md
> +substrateApi.tx.spaces.createSpace(content, permissionsOpt)
I think need to add `profiles.setProfile` too

2022-11-15 00:39 UTC, 0xMenna01 commented on docs/develop/how-to-guides/profiles/CreateProfiles.md
> +substrateApi.tx.spaces.createSpace(content, permissionsOpt)
done thank you.

2022-11-23 11:19 UTC, olehmell approved these changes

2022-11-23 11:21 UTC, merged