added docs restructuring
dappforce/subsocial-docs pull request #81
Opened 2022-12-30 11:18 UTC by tusharojha

2023-01-02 12:57 UTC, olehmell requested changes

2023-01-02 12:57 UTC, olehmell commented on docs/develop/SDKCheatsheet.md
> +const authHeader = 'c3ViLTVGQTluUURWZzI2N0RFZDhtMVp5cFhMQm52TjdTRnhZd1Y3bmRxU1lHaU45VFRwdToweDEwMmQ3ZmJhYWQwZGUwNzFjNDFmM2NjYzQzYmQ0NzIxNzFkZGFiYWM0MzEzZTc5YTY3ZWExOWM0OWFlNjgyZjY0YWUxMmRlY2YyNzhjNTE
Let's use it in all places instead of generateCrustAuthToken.

2023-01-02 12:57 UTC, olehmell commented on docs/develop/SDKCheatsheet.md
>  import { generateCrustAuthToken } from "@subsocial/api/utils/ipfs";
Remove the unused import

2023-01-03 14:44 UTC, olehmell approved these changes

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +We have a set of bounties we would love you to build.
```suggestion
We have a set of bounties we would love for you to build. 
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +Before starting to build, join our [Telegram](https://t.me/+ZzvLu0ZfkQwxNGQy) & [Discord](https://discord.gg/AnfSdfjy) channels to discuss with us.
```suggestion
Before starting to build, join our developer channels on [Telegram](https://t.me/+ZzvLu0ZfkQwxNGQy) & [Discord](https://discord.gg/MSW4xuvTE2) to discuss with us. 
```
Previous discord link had expired, this one will last forever

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +- Domains have several values attached to them, like spaces on the network, URL of projects, etc.
```suggestion
- Domains have several values attached to them, like spaces on the network, URLs of projects, etc. 
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +- We want you to create a browser extension that will resolve these domains from the browser’s search bar and navigate user directly to the linked website.
```suggestion
- We want you to create a browser extension that will resolve these domains from the browser’s search bar and navigate users directly to the linked website. 
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +- The extension should show the list of domains owned by an address. Ability to save your address to see and explore the domains you own.
```suggestion
- The extension should show the list of domains owned by an address, and let you save your address in order to see and explore the domains you own.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +- It needs to mark whether a domain is parked free or owned by a particular address. If available, then redirect to domain buy page.
```suggestion
- It needs to mark whether a domain is available, or owned by a particular address. If available, then redirect to the domain buy page.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +- You can use Subsocial JS SDK and our docs to do it.
```suggestion
- You can use the Subsocial JS SDK and our docs to do it.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +[IBC Media](https://ibc.media/hackathon-2) is a open to all hackathon organized in Hybrid Mode in India and Remotely.
```suggestion
[IBC Media](https://ibc.media/hackathon-2) is a hybrid open-to-all hackathon that takes place in India and online. 
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +We are sponsoring for the following bounties:
```suggestion
We are sponsoring the following bounties:
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/Bounties.md
> +#### Browser Extension to Resolve Subsocial Domains
copy the above section after making the changes

2023-01-03 18:44 UTC, Yung-Beef commented on docs/basics/faq/Overview.md
>  To learn about why Subsocial is launching as a parachain, please read
```suggestion
To learn about why Subsocial launched as a parachain, please read 
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/AboutSubsocial.md
> +The Subsocial SDK is a set of developments tools (methods, functions and so on) that allows to create your own social network on Subsocial.
```suggestion
The Subsocial SDK is a set of developments tools (methods, functions, and so on) that allows you to create your own social network on Subsocial.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/AboutSubsocial.md
> +In order to have an understanding of the SDK it is not necessary to know the implementation of the substrate based pallets that compose Subsocial. However, understanding the relations between Subsoci
```suggestion
In order to have an understanding of the SDK it is not necessary to know the implementation of the substrate based pallets that compose Subsocial. However, understanding the relationships between Subsocial entities can help you build within the SDK.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/AboutSubsocial.md
> +  - A space is the basic building block for Subsocial, it is where content lives.
```suggestion
  - A space is the basic building block for Subsocial, where content lives. 
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/AboutSubsocial.md
> +  - Posts and Comments are the building blocks that allow you to store content on Subsocial(whether that is text, audio, an image, or a video).
```suggestion
  - Posts and Comments are the building blocks that allow you to store content on Subsocial (whether that is text, audio, images, or videos).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/AboutSubsocial.md
> +  - Reactions enable the ability of reacting posts and comments, through upvotes and downvotes.
```suggestion
  - Reactions enable reacting to posts and comments, through upvotes and downvotes.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/AboutSubsocial.md
> +  - Usernames are crucial for social network dApps because they enable the mapping of human-readable usernames onto account addresses.
```suggestion
  - Usernames are crucial for social networking dApps because they enable the mapping of human-readable usernames onto account addresses.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/Developers.md
> +- To have a deeper look into how things work and available features, try our own social network: [Polkaverse App](https://polkaverse.com). Try to use the project and engage with people in the communi
```suggestion
- To have a deeper look into how things work and available features, try our own social network: [Polkaverse](https://polkaverse.com). Try to use the project and engage with people in the community.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/Developers.md
> +- To create your first Dapp in minutes, use the **Subsocial Starter** template [Read More](/docs/develop/developer-quickstart)
```suggestion
- To create your first Dapp in minutes, use the **Subsocial Starter** template. [Read More](/docs/develop/developer-quickstart)
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/Introduction.md
> +| [Start here](/docs/develop/about-subsocial)                    | Introduction to the Subsocial Technology and it's building blocks.                                                              |
```suggestion
| [Start here](/docs/develop/about-subsocial)                    | Introduction to the Subsocial Technology and its building blocks.                                                              |
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Read more about signing & sending transaction [here](/docs/develop/sdk/transactions)
```suggestion
Read more about signing & sending transactions [here](/docs/develop/sdk/transactions).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +To store data on IPFS, it is necessary to setup CRUST IPFS account and pushing the data from your account.
```suggestion
To store data on IPFS, it is necessary to set up a CRUST IPFS account and push the data from your account. 
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +> This is only required for Testnet. On Mainnet, this will not work.
```suggestion
> This is only required for the Testnet. On the Mainnet, this will not work.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Check full docs [here](/docs/develop/sdk/spaces/create-spaces).
```suggestion
Check the full docs [here](/docs/develop/sdk/spaces/create-spaces).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Check full docs [here](/docs/develop/sdk/posts/create-posts).
```suggestion
Check the full docs [here](/docs/develop/sdk/posts/create-posts).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Now, create a new space as mentioned [here](http://docs.subsocial.network/docs/develop/sdk-cheatsheet#space-1). So we can mark it as profile.
```suggestion
Now, create a new space as mentioned [here](http://docs.subsocial.network/docs/develop/sdk-cheatsheet#space-1), so we can mark it as a profile.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Check full docs [here](/docs/develop/sdk/profiles/create-profiles).
```suggestion
Check the full docs [here](/docs/develop/sdk/profiles/create-profiles).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Check full docs [here](/docs/develop/sdk/comments/fetch-comments).
```suggestion
Check the full docs [here](/docs/develop/sdk/comments/fetch-comments).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Check full docs [here](/docs/develop/sdk/follow/fetch-follow).
```suggestion
Check the full docs [here](/docs/develop/sdk/follow/fetch-follow).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Check full docs [here](/docs/develop/sdk/follow/create-follow).
```suggestion
Check the full docs [here](/docs/develop/sdk/follow/create-follow).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/SDKCheatsheet.md
> +Check full docs [here](/docs/develop/sdk/reactions/create-reactions).
```suggestion
Check the full docs [here](/docs/develop/sdk/reactions/create-reactions).
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/UnderstandingTestnet.md
> +title: About Testnet
```suggestion
title: About The Testnet
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/sdk/Transactions.md
> +> If you are new to the Polkadot ecosystem and want help to understand the Polkadot{.js} extension, read this [doc](/docs/tutorials/).
Can we just delete this entire section and talk about Talisman and SubWallet instead? Polkadot.js is trash

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/sdk/Transactions.md
> +Add these methods to interact with polkadotjs wallet:
```suggestion
Add these methods to interact with the polkadot.js wallet:
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/sdk/Transactions.md
> +// Fetch list of available accounts from the polkadotjs extension.
```suggestion
// Fetch list of available accounts from the polkadot.js extension.
```

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/sdk/Transactions.md
> +    throw Error(`Browser do not have any polkadot.js extension`)
Not sure if this code is used elsewhere, but it should be "Browser does not"

2023-01-03 18:44 UTC, Yung-Beef commented on docs/develop/sdk/Transactions.md
> +    throw Error(`Polkadot Extension have not authorized us to get accounts`)
Should be "has" instead of "have"

2023-01-03 18:44 UTC, Yung-Beef commented on docusaurus.config.js
> +          label: '📖 Dotsama Tutorials',
```suggestion
          label: '📖 User Tutorials',
```

2023-01-03 18:44 UTC, Yung-Beef commented on docusaurus.config.js
> +          label: '📖 Dotsama Tutorials',
Also need to update the Basics header to Protocol

2023-01-11 13:29 UTC, merged